### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by abeq** [domaframework/spring-boot-jpetstore#27]
I tried  as Read me:
'git clone' and './gradle bootRun' 
but return followings:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':bootRun'.
> No main class specified

Please let me know cause and way to fix it.
Thank you.

**Comment by nakamura-to** [comment]
Try `./gradlew bootRun` instead of `./gradle bootRun`.
It works without any problems in my environment.

If you can't solve the problem, try `./gradlew -d bootRun` and tell me details.

**Comment by abeq** [comment]
I appreciate for your advise and apologize for my mistake.
